name: Loc Binh News Bot

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"
    - cron: "0 0 * * *"

permissions:
  contents: write

concurrency:
  group: loc-binh-news
  cancel-in-progress: false

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install libraries
        run: |
          pip install -r requirements.txt

      - - name: Chạy bot
  env:
    TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  run: python bot.py

      - name: Save bot data
        run: |
          git config user.name "loc-binh-news-bot"
          git config user.email "bot@users.noreply.github.com"

          git add subscribers.json last_update_id.txt

          git diff --cached --quiet || git commit -m "Update bot data"

          git push
